/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreasy;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruhul
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tabbedArea = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 28, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 28, 29));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 28, 29));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("T");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 28, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("O");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 28, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("R");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 28, 29));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("S");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 28, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("W");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 291, -1, 29));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("O");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 326, 28, 29));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("R");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 361, 28, 29));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("L");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 396, 28, 29));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("D");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 431, 28, 29));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" '");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 28, 29));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cardiogram_icon-icons.com_66072.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 472));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        tabbedArea.addTab("Admin Panel", jPanel3);

        jPanel1.add(tabbedArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, -1, -1));

        jMenuBar2.setBackground(new java.awt.Color(0, 255, 255));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jMenuBar2.setForeground(new java.awt.Color(204, 255, 255));
        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar2.setPreferredSize(new java.awt.Dimension(200, 30));

        jMenu3.setText("Over View");

        jMenu2.setText("Doctor List");

        jMenuItem3.setText("Dermatologist ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Urologist");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem1.setText("Gastroenterologist");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Orthopedist");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Emergency Physician");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Surgeon");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Nephrologist");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Oncologists");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Cardiologist");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Anesthesiologists");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Rheumatologists");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Medicine");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenu3.add(jMenu2);

        jMenuItem5.setText("Patient List");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("Security");
        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    JPanel createPatientPanel(){
 
        JPanel temPanel = new JPanel();
        temPanel.setBackground(new Color(0,204,204));
        temPanel.setLayout(null);
    
    
        // Close Button code
       JButton cancel = new JButton("Close");      
       cancel.setBounds(5,5 ,100,30);
       temPanel.add(cancel);
       
       
       cancel.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
              int index = tabbedArea.getSelectedIndex();
              tabbedArea.remove(index);
        }
        });
       //-------------- Close button cod end ---------------------------
       
       
       //--------- Reload ----------
       
       JButton reload = new JButton("Reload");      
       reload.setBounds(580,5 ,100,30);
       temPanel.add(reload);
       
       reload.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
            int index = tabbedArea.getSelectedIndex();
          
                    
                    tabbedArea.remove(index);
                    tabShowPatientList();
        }
        });
              
//       
//       // -------- Reload end -------
        
               // Creating doctor list data table
       JTable tempTable = new JTable();
       
       String columnName[] = {"DoctorsID", "Name", "Age", "Number"};
        
        DefaultTableModel  darmaDoctorModel = new DefaultTableModel(columnName, 0);
        
        String query = "select *from patientlist";
        
        System.out.println(query);
        
        try{
            ResultSet rs = DBUTILS.queryExecute(query);
            
            while(rs.next()){
                String id = rs.getString("DoctorsID");
                String name = rs.getString("Name");
                String age = rs.getString("Age");
                String number = rs.getString("Number");
                
                
                String tempData[] = {id, name, age, number};
                darmaDoctorModel.addRow(tempData);
                
            }
            tempTable.setModel(darmaDoctorModel);
            
            
        
        }catch (Exception e){
           e.printStackTrace();
        }
        
        
        JScrollPane tempScrollTable;  
        tempScrollTable = new JScrollPane(tempTable);
        tempScrollTable.setBounds(5, 40, 677, 300);
        temPanel.add(tempScrollTable);
        // Table code end
        
        
        return temPanel;
    
    
    }
    
    
    
    
    private void tabShowPatientList(){
    
        JPanel temPanel = createPatientPanel();
        JLabel tabTItleLable = new JLabel("Patientlist");
        tabbedArea.addTab("Patientlist ",temPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        tabShowPatientList();
             
    }//GEN-LAST:event_jMenuItem5ActionPerformed
     
   
   JPanel createPanel(String databaseTableName){
       final String dbName = databaseTableName;
       
       JPanel temPanel = new JPanel();
       temPanel.setBackground(new Color(0,204,204));
       temPanel.setLayout(null);
       
       JScrollPane tempScrollTable;
       
       // Close Button code
       JButton cancel = new JButton("Close");      
       cancel.setBounds(5,5 ,100,30);
       temPanel.add(cancel);
       
       
       cancel.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
              int index = tabbedArea.getSelectedIndex();
              tabbedArea.remove(index);
        }
        });
       //-------------- Close button cod end ---------------------------
       
       
       //--------- Reload ----------
       
       JButton reload = new JButton("Reload");      
       reload.setBounds(580,5 ,100,30);
       temPanel.add(reload);
       
       reload.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
            int index = tabbedArea.getSelectedIndex();
            switch (dbName) {
                case "dermatologisttable":
                    
                    tabbedArea.remove(index);
                    tabShowDerma();
                    break;
                case "urologisttable":
                    tabbedArea.remove(index);
                    tabShowUro();
                    break;
                case "gastroenterologisttable":
                    tabbedArea.remove(index);
                    tabShowGas();
                    break;
                case "cardiologisttable":
                    tabbedArea.remove(index);
                    tabShowCar();
                    break;
                case "orthopedisttable":
                    tabbedArea.remove(index);
                    tabShowOrtho();
                    break;
                case "emergencyphysiciantable":
                    tabbedArea.remove(index);
                    tabShowEmer();
                    break;
                case "surgeontable":
                    tabbedArea.remove(index);
                    tabShowSur();
                    break;
                case "nephrologisttable":
                    tabbedArea.remove(index);
                    tabShowNep();
                    break;
                case "oncologiststable":
                    tabbedArea.remove(index);
                    tabShowOnco();
                    break;
                case "anesthesiologiststable":
                    tabbedArea.remove(index);
                    tabShowAnes();
                    break;
                case "rheumatologiststable":
                    tabbedArea.remove(index);
                    tabShowRhe();
                    break;
                case "medicinetable":
                    tabbedArea.remove(index);
                    tabShowMed();
                    break;
            }
        }
        });
       
       
       // -------- Reload end -------
       
       
       
       //------------- insert button --------------------------
       
       // ------------ Control Label-------
       
       JLabel controlTitle = new JLabel();
       controlTitle.setText("Control Section: ");
       controlTitle.setBounds(9, 340, 200, 30);
       temPanel.add(controlTitle);
       
       // ------------End controll Lable-----
       
       JButton insert = new JButton("Insert new Doctor Info");
       insert.setBounds(20,375 ,200,30);
       temPanel.add(insert);
       
       
        insert.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
              InsertlSection controlInsert;
              controlInsert = new InsertlSection(dbName);
              controlInsert.setVisible(true);
        }
        });
       
       //-----------------end insert--------------------------
       
       
       
       //--------------------- update button ---------------------
       
       JButton update = new JButton("Update Doctor Info");
       update.setBounds(250,375 ,200,30);
       temPanel.add(update);
       
       update.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          {
              Updateframe controlUpdate;
              controlUpdate = new Updateframe(dbName);
              controlUpdate.setVisible(true);
        }
        });
       
       
       //-----------------------end update------------------------
       
       
       
       //------------- delete button -------------------------------
       
       JButton delete = new JButton("Delete  Doctor Info");
       delete.setBounds(480,375 ,200,30);
       temPanel.add(delete);
       delete.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae)
          
        {
              DeleteFrame deleteFrame = new DeleteFrame (dbName);
              
              deleteFrame.setVisible(true);          
              
        }
        });
       
       //-------------end delete button ------------------------

       
       // Creating doctor list data table
       JTable tempTable = new JTable();
       
       String columnName[] = {"DoctorsID", "Name", "Chamber Location", "Chamber Time", "Visiting Fee"};
        
        DefaultTableModel  darmaDoctorModel = new DefaultTableModel(columnName, 0);
        
        String query = "select *from " + databaseTableName;
        
        System.out.println(query);
        
        try{
            ResultSet rs = DBUTILS.queryExecute(query);
            
            while(rs.next()){
                String id = rs.getString("DoctorsID");
                String name = rs.getString("Name");
                String location = rs.getString("Chamber Location");
                String time = rs.getString("Chamber Time");
                String fee = rs.getString("Visiting Fee");
                
                String tempData[] = {id, name, location, time, fee};
                darmaDoctorModel.addRow(tempData);
                
            }
            tempTable.setModel(darmaDoctorModel);
            
            
        
        }catch (Exception e){
           e.printStackTrace();
        }
              
        tempScrollTable = new JScrollPane(tempTable);  
        tempScrollTable.setBounds(5, 40, 677, 300);
        temPanel.add(tempScrollTable);
        // Table code end
        
       
       
       
        return temPanel;
       
    }
    
   // Menu click show tab code start
   
    public void tabShowDerma(){
        JLabel tabTItleLable = new JLabel("Dermatologist");
        JPanel tabPanel = createPanel("dermatologisttable");
        
        tabbedArea.addTab("Dermatologist ",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        tabShowDerma();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    private void tabShowUro(){
    
        JLabel tabTItleLable = new JLabel("Urologist");
        JPanel tabPanel = createPanel("urologisttable");
        
        tabbedArea.addTab("Urologist ",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        tabShowUro();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    private void tabShowGas(){
    
        JLabel tabTItleLable = new JLabel("Gastroenterologist");
        JPanel tabPanel = createPanel("gastroenterologisttable");
        
        tabbedArea.addTab("Gastroenterologist ",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
         tabShowGas();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void tabShowNep(){
       
        JLabel tabTItleLable = new JLabel("Nephrologist");
        JPanel tabPanel = createPanel("nephrologisttable");
        
        tabbedArea.addTab("Nephrologist",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        tabShowNep();
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    
    private void tabShowOnco(){
    
        JLabel tabTItleLable = new JLabel("Oncologists");
        JPanel tabPanel = createPanel("oncologiststable");
        
        tabbedArea.addTab("Oncologists",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    }
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        tabShowOnco();
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    
    private void tabShowRhe(){
    
        
        JLabel tabTItleLable = new JLabel("Rheumatologists");
        JPanel tabPanel = createPanel("rheumatologiststable");
        
        tabbedArea.addTab("Rheumatologists",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        
        tabShowRhe();
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    
    private void tabShowOrtho(){
    
        JLabel tabTItleLable = new JLabel("Orthopedist");
        JPanel tabPanel = createPanel("orthopedisttable");
        
        tabbedArea.addTab("Orthopedist ",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        tabShowOrtho();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void tabShowEmer(){
        
        JLabel tabTItleLable = new JLabel("Emergency Physician");
        JPanel tabPanel = createPanel("emergencyphysiciantable");
        
        tabbedArea.addTab("Emergency Physician ",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
        
    }
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
        tabShowEmer();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void tabShowSur(){
    
         JLabel tabTItleLable = new JLabel("Surgeon");
        JPanel tabPanel = createPanel("surgeontable");
        
        tabbedArea.addTab("Surgeon",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       tabShowSur();
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    private void tabShowCar(){
    
        JLabel tabTItleLable = new JLabel("Cardiologist");
        JPanel tabPanel = createPanel("cardiologisttable");
        
        tabbedArea.addTab("Cardiologist",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        tabShowCar();
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    
    private void tabShowAnes(){
    
        JLabel tabTItleLable = new JLabel("Anesthesiologists");
        JPanel tabPanel = createPanel("anesthesiologiststable");
        
        tabbedArea.addTab("Anesthesiologists",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    }
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        tabShowAnes();
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    
    private void tabShowMed(){
    
        JLabel tabTItleLable = new JLabel("Medicine");
        JPanel tabPanel = createPanel("medicinetable");
        
        tabbedArea.addTab("Medicine",tabPanel);
        tabbedArea.setTabComponentAt(tabbedArea.getTabCount() - 1, tabTItleLable);
        tabbedArea.setSelectedIndex(tabbedArea.getTabCount() - 1);
    
    }
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        tabShowMed();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    
    // Show tab code end
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane tabbedArea;
    // End of variables declaration//GEN-END:variables
}
