/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreasy;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruhul
 */
public class DepartMent extends javax.swing.JFrame {

    /**
     * Creates new form DepartMent
     */
    public DepartMent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dermaLable = new javax.swing.JLabel();
        uroLabel = new javax.swing.JLabel();
        gastroLabel = new javax.swing.JLabel();
        orthoLabel = new javax.swing.JLabel();
        cardioLabel = new javax.swing.JLabel();
        emergencyLabel = new javax.swing.JLabel();
        nephroLabel = new javax.swing.JLabel();
        surgLabel = new javax.swing.JLabel();
        oncolocistsLabel = new javax.swing.JLabel();
        anesthesiologistsLabel = new javax.swing.JLabel();
        rheumatologistsLabel = new javax.swing.JLabel();
        medicineLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(95, 226, 231));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Titillium Bd", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOCTOR'S WORLD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cardiogram_icon-icons.com_66072.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 82));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("   Select Department ");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        dermaLable.setBackground(new java.awt.Color(0, 255, 255));
        dermaLable.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        dermaLable.setText("   Dermatologist ");
        dermaLable.setToolTipText("Select Department");
        dermaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dermaLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dermaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dermaLableClicked(evt);
            }
        });

        uroLabel.setBackground(new java.awt.Color(0, 255, 255));
        uroLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        uroLabel.setText("  Urologist");
        uroLabel.setToolTipText("Select Department");
        uroLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        uroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uroClicked(evt);
            }
        });

        gastroLabel.setBackground(new java.awt.Color(0, 255, 255));
        gastroLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        gastroLabel.setText("  Gastroenterologist");
        gastroLabel.setToolTipText("Select Department");
        gastroLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gastroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gastroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gastroClicked(evt);
            }
        });

        orthoLabel.setBackground(new java.awt.Color(0, 255, 255));
        orthoLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        orthoLabel.setText("  Orthopedist");
        orthoLabel.setToolTipText("Select Department");
        orthoLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        orthoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orthoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orthopedClicked(evt);
            }
        });

        cardioLabel.setBackground(new java.awt.Color(0, 255, 255));
        cardioLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        cardioLabel.setText("   Cardiologist");
        cardioLabel.setToolTipText("Select Department");
        cardioLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cardioLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardioLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardioClicked(evt);
            }
        });

        emergencyLabel.setBackground(new java.awt.Color(0, 255, 255));
        emergencyLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        emergencyLabel.setText("  Emergency Physician");
        emergencyLabel.setToolTipText("Select Department");
        emergencyLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        emergencyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emergencyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emergencyClicked(evt);
            }
        });

        nephroLabel.setBackground(new java.awt.Color(0, 255, 255));
        nephroLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        nephroLabel.setText("  Nephrologist");
        nephroLabel.setToolTipText("Select Department");
        nephroLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nephroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nephroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nephroClicked(evt);
            }
        });

        surgLabel.setBackground(new java.awt.Color(0, 255, 255));
        surgLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        surgLabel.setText("   Surgeon");
        surgLabel.setToolTipText("Select Department");
        surgLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        surgLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        surgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surgeonClicked(evt);
            }
        });

        oncolocistsLabel.setBackground(new java.awt.Color(0, 255, 255));
        oncolocistsLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        oncolocistsLabel.setText("  Oncologists");
        oncolocistsLabel.setToolTipText("Select Department");
        oncolocistsLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        oncolocistsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oncolocistsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oncoloClicked(evt);
            }
        });

        anesthesiologistsLabel.setBackground(new java.awt.Color(0, 255, 255));
        anesthesiologistsLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        anesthesiologistsLabel.setText("   Anesthesiologists");
        anesthesiologistsLabel.setToolTipText("Select Department");
        anesthesiologistsLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        anesthesiologistsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anesthesiologistsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anesthesiologistClicked(evt);
            }
        });

        rheumatologistsLabel.setBackground(new java.awt.Color(0, 255, 255));
        rheumatologistsLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        rheumatologistsLabel.setText("  Rheumatologists");
        rheumatologistsLabel.setToolTipText("Select Department");
        rheumatologistsLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        rheumatologistsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rheumatologistsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rheuClicked(evt);
            }
        });

        medicineLabel.setBackground(new java.awt.Color(0, 255, 255));
        medicineLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        medicineLabel.setText("  Medicine");
        medicineLabel.setToolTipText("Select Department");
        medicineLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        medicineLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicineLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicineClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dermaLable, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anesthesiologistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(orthoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(nephroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(rheumatologistsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gastroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oncolocistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dermaLable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gastroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orthoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nephroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oncolocistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anesthesiologistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rheumatologistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dermaLableClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dermaLableClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = dermaLable.getText();
        this.setVisible(false);
        doclist.showDarmaTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_dermaLableClicked

    private void uroClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uroClicked
//        DoctorListView doclist = new DoctorListView();
//        
        // self code
        
//        String deptName = uroLabel.getText();
//        this.setVisible(false);
//        doclist.showUroTable(deptName);       
//        doclist.setVisible(true);
    }//GEN-LAST:event_uroClicked

    private void gastroClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = gastroLabel.getText();
        this.setVisible(false);
        doclist.showGastroTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_gastroClicked

    private void cardioClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardioClicked
        
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = cardioLabel.getText();
        this.setVisible(false);
        doclist.showCardioTable(deptName);       
        doclist.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_cardioClicked

    private void orthopedClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orthopedClicked
        
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = orthoLabel.getText();
        this.setVisible(false);
        doclist.showOrthopedTable(deptName);       
        doclist.setVisible(true);
        
        
        
    }//GEN-LAST:event_orthopedClicked

    private void emergencyClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emergencyClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = emergencyLabel.getText();
        this.setVisible(false);
        doclist.showEmergencyTable(deptName);       
        doclist.setVisible(true);
        
        
        
    }//GEN-LAST:event_emergencyClicked

    private void surgeonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surgeonClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = surgLabel.getText();
        this.setVisible(false);
        doclist.showSurgeonTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_surgeonClicked

    private void nephroClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nephroClicked
        
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = nephroLabel.getText();
        this.setVisible(false);
        doclist.showNephrologistTable(deptName);       
        doclist.setVisible(true);
        
        
        
    }//GEN-LAST:event_nephroClicked

    private void oncoloClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oncoloClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = oncolocistsLabel.getText();
        this.setVisible(false);
        doclist.showOncologistsTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_oncoloClicked

    private void anesthesiologistClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anesthesiologistClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = anesthesiologistsLabel.getText();
        this.setVisible(false);
        doclist.showAnesthesiologistsTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_anesthesiologistClicked

    private void rheuClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rheuClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = rheumatologistsLabel.getText();
        this.setVisible(false);
        doclist.showRheumatologistsTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_rheuClicked

    private void medicineClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineClicked
        DoctorListView doclist = new DoctorListView();
        
        // self code
        
        String deptName = medicineLabel.getText();
        this.setVisible(false);
        doclist.showMedicineTable(deptName);       
        doclist.setVisible(true);
    }//GEN-LAST:event_medicineClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartMent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartMent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartMent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartMent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartMent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anesthesiologistsLabel;
    private javax.swing.JLabel cardioLabel;
    private javax.swing.JLabel dermaLable;
    private javax.swing.JLabel emergencyLabel;
    private javax.swing.JLabel gastroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel medicineLabel;
    private javax.swing.JLabel nephroLabel;
    private javax.swing.JLabel oncolocistsLabel;
    private javax.swing.JLabel orthoLabel;
    private javax.swing.JLabel rheumatologistsLabel;
    private javax.swing.JLabel surgLabel;
    private javax.swing.JLabel uroLabel;
    // End of variables declaration//GEN-END:variables
}
