/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreasy;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruhul
 */
public class DoctorListView extends javax.swing.JFrame {

    /**
     * Creates new form DoctorListView
     */
    public DoctorListView() {
        initComponents();
    }
    
    
    //self made section start
    
    private void showTable(String databaseTableName){
    
//    System.out.println(databaseTableName);
    
    String columnName[] = {"DoctorsID", "Name", "Chamber Location", "Chamber Time", "Visiting Fee"};
        
        DefaultTableModel  darmaDoctorModel = new DefaultTableModel(columnName, 0);
        
        String query = "select *from " + databaseTableName;
        
        System.out.println(query);
        
        try{
            ResultSet rs = DBUTILS.queryExecute(query);
            
            while(rs.next()){
                String id = rs.getString("DoctorsID");
                String name = rs.getString("Name");
                String location = rs.getString("Chamber Location");
                String time = rs.getString("Chamber Time");
                String fee = rs.getString("Visiting Fee");
                
                String tempData[] = {id, name, location, time, fee};
                darmaDoctorModel.addRow(tempData);
                
            }
            doctorlistTable.setModel(darmaDoctorModel);
        
        }catch (Exception e){
           e.printStackTrace();
        }
    
    
    }
    
    String dbName;
    
    public void showDarmaTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "dermatologisttable";
        showTable(dbName);
    
    
    }
    
    public void showUroTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "urologisttable";
        showTable(dbName);
    
    
    }
    
    public void showGastroTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "gastroenterologisttable";
        showTable(dbName);
    
    
    }
    
    public void showCardioTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "cardiologisttable";
        showTable(dbName);
    
    
    }
    
    public void showOrthopedTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "orthopedisttable";
        showTable(dbName);
    
    
    }
    
    public void showEmergencyTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "emergencyphysiciantable";
        showTable(dbName);
    
    
    }
    
    public void showSurgeonTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "surgeontable";
        showTable(dbName);
    
    
    }
    
    
    public void showNephrologistTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "nephrologisttable";
        showTable(dbName);
    
    
    }
    
    
    public void showOncologistsTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "oncologiststable";
        showTable(dbName);
    
    
    }
    
    public void showAnesthesiologistsTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "anesthesiologiststable";
        showTable(dbName);
    
    
    }
    
    public void showRheumatologistsTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "rheumatologiststable";
        showTable(dbName);
    
    
    }
    
    public void showMedicineTable(String deptName){
        
        titleDoctorList.setText(deptName + " Department's Doctor List :");
        
        dbName = "medicinetable";
        showTable(dbName);
    
    
    }
    
    //self made section end

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        doctorIdInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        backButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleDoctorList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorlistTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Titillium Bd", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Doctor ID : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        doctorIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorIdInputActionPerformed(evt);
            }
        });
        jPanel2.add(doctorIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 157, 29));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(Pressed Continue to get appointment)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        continueButton.setBackground(new java.awt.Color(255, 255, 255));
        continueButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        continueButton.setText("Continue ");
        continueButton.setToolTipText("Click to Continue");
        continueButton.setBorder(new javax.swing.border.MatteBorder(null));
        continueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        jPanel2.add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 104, 22));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back4_89388.png"))); // NOI18N
        backButton.setToolTipText("Back to Doctor List");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backClicked(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 346, -1, -1));

        jPanel3.setBackground(new java.awt.Color(95, 226, 231));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Titillium Bd", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOCTOR'S WORLD");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cardiogram_icon-icons.com_66072.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        titleDoctorList.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleDoctorList.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleDoctorList, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleDoctorList, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        doctorlistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Name", "Chamber Location", "Chamber Time", "Visiting Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorlistTable.setRowHeight(25);
        doctorlistTable.setShowHorizontalLines(false);
        doctorlistTable.setShowVerticalLines(false);
        doctorlistTable.getTableHeader().setResizingAllowed(false);
        doctorlistTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(doctorlistTable);
        if (doctorlistTable.getColumnModel().getColumnCount() > 0) {
            doctorlistTable.getColumnModel().getColumn(0).setResizable(false);
            doctorlistTable.getColumnModel().getColumn(1).setResizable(false);
            doctorlistTable.getColumnModel().getColumn(2).setResizable(false);
            doctorlistTable.getColumnModel().getColumn(3).setResizable(false);
            doctorlistTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorIdInputActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
       
        String selectedid = doctorIdInput.getText();
        
        GetAppointment getAppointment;
        getAppointment = new GetAppointment(selectedid,dbName);
        
        this.setVisible(false);
        getAppointment.setVisible(true);
    }//GEN-LAST:event_continueButtonActionPerformed

    private void backClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backClicked
        this.setVisible(false);
        
        DepartMent backToDepartmentList = new DepartMent();
        backToDepartmentList.setVisible(true);
    }//GEN-LAST:event_backClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JTextField doctorIdInput;
    private javax.swing.JTable doctorlistTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleDoctorList;
    // End of variables declaration//GEN-END:variables
}
